const quizData = [
  { q: "¿Cuál es el asteroide más cercano a la Tierra?", options: ["Apophis", "Eros", "Ceres"], answer: "Apophis" },
  { q: "¿Qué mide la escala de Torino?", options: ["Tamaño del asteroide", "Riesgo de impacto", "Composición química"], answer: "Riesgo de impacto" },
  { q: "¿Cuál es el planeta más grande del sistema solar?", options: ["Júpiter", "Saturno", "Neptuno"], answer: "Júpiter" },
  { q: "¿Cuál es el satélite natural de la Tierra?", options: ["La Luna", "Io", "Titán"], answer: "La Luna" },
  { q: "¿Qué planeta es conocido como el planeta rojo?", options: ["Marte", "Venus", "Mercurio"], answer: "Marte" },
  { q: "¿Qué es un exoplaneta?", options: ["Un planeta fuera del sistema solar", "Un satélite natural", "Un asteroide grande"], answer: "Un planeta fuera del sistema solar" },
  { q: "¿Cuál es la estrella más cercana a la Tierra después del Sol?", options: ["Proxima Centauri", "Sirius", "Betelgeuse"], answer: "Proxima Centauri" },
  { q: "¿Qué es un cometa?", options: ["Un cuerpo de hielo y polvo que orbita el Sol", "Un asteroide metálico", "Una estrella fugaz"], answer: "Un cuerpo de hielo y polvo que orbita el Sol" },
  { q: "¿Qué planeta tiene los anillos más visibles?", options: ["Saturno", "Júpiter", "Urano"], answer: "Saturno" },
  { q: "¿Qué planeta es el más cercano al Sol?", options: ["Mercurio", "Venus", "Marte"], answer: "Mercurio" },
  { q: "¿Qué es un agujero negro?", options: ["Una región con gravedad tan fuerte que nada escapa", "Una estrella enana", "Un planeta muerto"], answer: "Una región con gravedad tan fuerte que nada escapa" },
  { q: "¿Cuál es la galaxia más cercana a la Vía Láctea?", options: ["Andrómeda", "Triángulo", "Sombrero"], answer: "Andrómeda" },
  { q: "¿Qué planeta es conocido por su color azul intenso?", options: ["Neptuno", "Urano", "Saturno"], answer: "Neptuno" },
  { q: "¿Qué es una supernova?", options: ["Explosión de una estrella al final de su vida", "Un planeta gigante", "Un cometa grande"], answer: "Explosión de una estrella al final de su vida" },
  { q: "¿Cuál es la unidad de distancia utilizada para medir distancias estelares?", options: ["Año luz", "Kilómetro", "Unidad astronómica"], answer: "Año luz" },
  { q: "¿Qué planeta tiene mayor gravedad que la Tierra?", options: ["Júpiter", "Marte", "Venus"], answer: "Júpiter" },
  { q: "¿Cuál es el planeta más pequeño del sistema solar?", options: ["Mercurio", "Plutón", "Marte"], answer: "Mercurio" },
  { q: "¿Qué es la nebulosa de Orión?", options: ["Una nube de gas y polvo donde nacen estrellas", "Un agujero negro cercano", "Un cometa"], answer: "Una nube de gas y polvo donde nacen estrellas" },
  { q: "¿Qué planeta tiene un día más largo que su año?", options: ["Venus", "Mercurio", "Marte"], answer: "Venus" },
  { q: "¿Qué es un asteroide?", options: ["Un cuerpo rocoso que orbita el Sol", "Un satélite artificial", "Una estrella pequeña"], answer: "Un cuerpo rocoso que orbita el Sol" },
  { q: "¿Qué planeta tiene más lunas conocidas?", options: ["Saturno", "Júpiter", "Urano"], answer: "Saturno" },
  { q: "¿Cuál es el principal componente del Sol?", options: ["Hidrógeno", "Helio", "Oxígeno"], answer: "Hidrógeno" },
  { q: "¿Qué es la Vía Láctea?", options: ["Nuestra galaxia", "Un cúmulo estelar", "Un cometa gigante"], answer: "Nuestra galaxia" },
  { q: "¿Qué fenómeno ocurre cuando la Luna se interpone entre el Sol y la Tierra?", options: ["Eclipse solar", "Eclipse lunar", "Aurora boreal"], answer: "Eclipse solar" },
  { q: "¿Qué planeta tiene la mayor velocidad orbital?", options: ["Mercurio", "Venus", "Júpiter"], answer: "Mercurio" },
  { q: "¿Cuál es el planeta con mayor inclinación axial?", options: ["Urano", "Neptuno", "Saturno"], answer: "Urano" },
  { q: "¿Qué es un cúmulo estelar?", options: ["Un grupo de estrellas unidas por gravedad", "Un agujero negro", "Un planeta con anillos"], answer: "Un grupo de estrellas unidas por gravedad" },
  { q: "¿Qué planeta es conocido como el gigante gaseoso?", options: ["Júpiter", "Saturno", "Neptuno"], answer: "Júpiter" },
  { q: "¿Qué fenómeno causa las auroras boreales?", options: ["Interacción del viento solar con la magnetosfera", "Explosión de supernova", "Rotación de la Luna"], answer: "Interacción del viento solar con la magnetosfera" },
  { q: "¿Qué planeta está más lejos del Sol?", options: ["Neptuno", "Urano", "Plutón"], answer: "Neptuno" },
  { q: "¿Qué estrella se considera la más brillante en el cielo nocturno?", options: ["Sirius", "Canopus", "Betelgeuse"], answer: "Sirius" },
  { q: "¿Qué es una enana blanca?", options: ["Restos de una estrella que agotó su combustible", "Un tipo de planeta", "Un asteroide gigante"], answer: "Restos de una estrella que agotó su combustible" },
  { q: "¿Qué planeta tiene el mayor campo magnético?", options: ["Júpiter", "Tierra", "Saturno"], answer: "Júpiter" },
  { q: "¿Qué planeta tiene la atmósfera más densa?", options: ["Venus", "Tierra", "Marte"], answer: "Venus" },
  { q: "¿Qué es un quásar?", options: ["Núcleo galáctico muy brillante", "Una estrella en explosión", "Un planeta lejano"], answer: "Núcleo galáctico muy brillante" },
  { q: "¿Qué planeta tiene un eje de rotación casi horizontal?", options: ["Urano", "Neptuno", "Saturno"], answer: "Urano" },
  { q: "¿Qué son los meteoritos?", options: ["Fragmentos de asteroides o cometas que caen a la Tierra", "Estrellas fugaces", "Cometas que se desintegran"], answer: "Fragmentos de asteroides o cometas que caen a la Tierra" },
  { q: "¿Cuál es la estrella más grande conocida?", options: ["UY Scuti", "Betelgeuse", "Rigel"], answer: "UY Scuti" },
  { q: "¿Qué planeta tiene temperaturas más extremas?", options: ["Mercurio", "Venus", "Marte"], answer: "Mercurio" },
  { q: "¿Qué planeta es conocido por su color amarillo dorado?", options: ["Saturno", "Júpiter", "Urano"], answer: "Saturno" },
  { q: "¿Qué es un púlsar?", options: ["Una estrella de neutrones que emite radiación periódica", "Un agujero negro activo", "Un cometa rápido"], answer: "Una estrella de neutrones que emite radiación periódica" },
  { q: "¿Qué planeta tiene la mayor densidad?", options: ["Tierra", "Mercurio", "Neptuno"], answer: "Tierra" },
  { q: "¿Qué es un tránsito planetario?", options: ["Paso de un planeta frente a su estrella", "Explosión estelar", "Rotación de una luna"], answer: "Paso de un planeta frente a su estrella" },
  { q: "¿Qué es una estrella variable?", options: ["Una estrella cuya luminosidad cambia con el tiempo", "Una estrella gigante azul", "Una enana blanca"], answer: "Una estrella cuya luminosidad cambia con el tiempo" },
  { q: "¿Qué planeta tiene los días más largos?", options: ["Venus", "Mercurio", "Marte"], answer: "Venus" },
  { q: "¿Qué planeta tiene los anillos más delgados?", options: ["Neptuno", "Saturno", "Urano"], answer: "Neptuno" },
  { q: "¿Qué es un agujero de gusano?", options: ["Una posible conexión entre dos puntos del espacio-tiempo", "Un agujero negro gigante", "Un cometa en órbita"], answer: "Una posible conexión entre dos puntos del espacio-tiempo" },
  { q: "¿Qué es un objeto transneptuniano?", options: ["Cualquier objeto más allá de Neptuno", "Un asteroide cercano a Júpiter", "Una estrella joven"], answer: "Cualquier objeto más allá de Neptuno" },
  { q: "¿Cuál es la composición principal de los cometas?", options: ["Hielo y polvo", "Gas metálico", "Rocas pesadas"], answer: "Hielo y polvo" },
  { q: "¿Qué planeta tiene el día más corto?", options: ["Júpiter", "Saturno", "Neptuno"], answer: "Júpiter" },
  { q: "¿Qué es un agujero negro supermasivo?", options: ["Un agujero negro en el centro de galaxias", "Un cometa gigante", "Una estrella de neutrones gigante"], answer: "Un agujero negro en el centro de galaxias" },
];

export default quizData;