const quizData = [
  { q: "Which is the closest asteroid to Earth?", options: ["Apophis", "Eros", "Ceres"], answer: "Apophis" },
  { q: "What does the Torino Scale measure?", options: ["Asteroid size", "Impact risk", "Chemical composition"], answer: "Impact risk" },
  { q: "Which is the largest planet in the solar system?", options: ["Jupiter", "Saturn", "Neptune"], answer: "Jupiter" },
  { q: "Which is the Earth's natural satellite?", options: ["The Moon", "Io", "Titan"], answer: "The Moon" },
  { q: "Which planet is known as the red planet?", options: ["Mars", "Venus", "Mercury"], answer: "Mars" },
  { q: "What is an exoplanet?", options: ["A planet outside the solar system", "A natural satellite", "A large asteroid"], answer: "A planet outside the solar system" },
  { q: "Which is the closest star to Earth after the Sun?", options: ["Proxima Centauri", "Sirius", "Betelgeuse"], answer: "Proxima Centauri" },
  { q: "What is a comet?", options: ["A body of ice and dust orbiting the Sun", "A metallic asteroid", "A shooting star"], answer: "A body of ice and dust orbiting the Sun" },
  { q: "Which planet has the most visible rings?", options: ["Saturn", "Jupiter", "Uranus"], answer: "Saturn" },
  { q: "Which planet is the closest to the Sun?", options: ["Mercury", "Venus", "Mars"], answer: "Mercury" },
  { q: "What is a black hole?", options: ["A region with gravity so strong nothing escapes", "A dwarf star", "A dead planet"], answer: "A region with gravity so strong nothing escapes" },
  { q: "Which is the closest galaxy to the Milky Way?", options: ["Andromeda", "Triangulum", "Sombrero"], answer: "Andromeda" },
  { q: "Which planet is known for its intense blue color?", options: ["Neptune", "Uranus", "Saturn"], answer: "Neptune" },
  { q: "What is a supernova?", options: ["Explosion of a star at the end of its life", "A giant planet", "A large comet"], answer: "Explosion of a star at the end of its life" },
  { q: "What is the unit of distance used to measure stellar distances?", options: ["Light year", "Kilometer", "Astronomical unit"], answer: "Light year" },
  { q: "Which planet has greater gravity than Earth?", options: ["Jupiter", "Mars", "Venus"], answer: "Jupiter" },
  { q: "Which is the smallest planet in the solar system?", options: ["Mercury", "Pluto", "Mars"], answer: "Mercury" },
  { q: "What is the Orion Nebula?", options: ["A cloud of gas and dust where stars are born", "A nearby black hole", "A comet"], answer: "A cloud of gas and dust where stars are born" },
  { q: "Which planet has a day longer than its year?", options: ["Venus", "Mercury", "Mars"], answer: "Venus" },
  { q: "What is an asteroid?", options: ["A rocky body that orbits the Sun", "An artificial satellite", "A small star"], answer: "A rocky body that orbits the Sun" },
  { q: "Which planet has the most known moons?", options: ["Saturn", "Jupiter", "Uranus"], answer: "Saturn" },
  { q: "What is the main component of the Sun?", options: ["Hydrogen", "Helium", "Oxygen"], answer: "Hydrogen" },
  { q: "What is the Milky Way?", options: ["Our galaxy", "A star cluster", "A giant comet"], answer: "Our galaxy" },
  { q: "What phenomenon occurs when the Moon passes between the Sun and the Earth?", options: ["Solar eclipse", "Lunar eclipse", "Aurora borealis"], answer: "Solar eclipse" },
  { q: "Which planet has the fastest orbital speed?", options: ["Mercury", "Venus", "Jupiter"], answer: "Mercury" },
  { q: "Which planet has the greatest axial tilt?", options: ["Uranus", "Neptune", "Saturn"], answer: "Uranus" },
  { q: "What is a star cluster?", options: ["A group of stars held together by gravity", "A black hole", "A planet with rings"], answer: "A group of stars held together by gravity" },
  { q: "Which planet is known as the gas giant?", options: ["Jupiter", "Saturn", "Neptune"], answer: "Jupiter" },
  { q: "What phenomenon causes the aurora borealis?", options: ["Interaction of solar wind with the magnetosphere", "Supernova explosion", "Rotation of the Moon"], answer: "Interaction of solar wind with the magnetosphere" },
  { q: "Which planet is farthest from the Sun?", options: ["Neptune", "Uranus", "Pluto"], answer: "Neptune" },
  { q: "Which star is considered the brightest in the night sky?", options: ["Sirius", "Canopus", "Betelgeuse"], answer: "Sirius" },
  { q: "What is a white dwarf?", options: ["Remains of a star that has exhausted its fuel", "A type of planet", "A giant asteroid"], answer: "Remains of a star that has exhausted its fuel" },
  { q: "Which planet has the largest magnetic field?", options: ["Jupiter", "Earth", "Saturn"], answer: "Jupiter" },
  { q: "Which planet has the densest atmosphere?", options: ["Venus", "Earth", "Mars"], answer: "Venus" },
  { q: "What is a quasar?", options: ["Very bright galactic nucleus", "An exploding star", "A distant planet"], answer: "Very bright galactic nucleus" },
  { q: "Which planet has a nearly horizontal rotation axis?", options: ["Uranus", "Neptune", "Saturn"], answer: "Uranus" },
  { q: "What are meteorites?", options: ["Fragments of asteroids or comets that fall to Earth", "Shooting stars", "Disintegrating comets"], answer: "Fragments of asteroids or comets that fall to Earth" },
  { q: "Which is the largest known star?", options: ["UY Scuti", "Betelgeuse", "Rigel"], answer: "UY Scuti" },
  { q: "Which planet has the most extreme temperatures?", options: ["Mercury", "Venus", "Mars"], answer: "Mercury" },
  { q: "Which planet is known for its golden yellow color?", options: ["Saturn", "Jupiter", "Uranus"], answer: "Saturn" },
  { q: "What is a pulsar?", options: ["A neutron star that emits periodic radiation", "An active black hole", "A fast comet"], answer: "A neutron star that emits periodic radiation" },
  { q: "Which planet has the highest density?", options: ["Earth", "Mercury", "Neptune"], answer: "Earth" },
  { q: "What is a planetary transit?", options: ["Passage of a planet in front of its star", "Star explosion", "Rotation of a moon"], answer: "Passage of a planet in front of its star" },
  { q: "What is a variable star?", options: ["A star whose luminosity changes over time", "A blue giant star", "A white dwarf"], answer: "A star whose luminosity changes over time" },
  { q: "Which planet has the longest days?", options: ["Venus", "Mercury", "Mars"], answer: "Venus" },
  { q: "Which planet has the thinnest rings?", options: ["Neptune", "Saturn", "Uranus"], answer: "Neptune" },
  { q: "What is a wormhole?", options: ["A possible connection between two points in spacetime", "A giant black hole", "An orbiting comet"], answer: "A possible connection between two points in spacetime" },
  { q: "What is a trans-Neptunian object?", options: ["Any object beyond Neptune", "An asteroid near Jupiter", "A young star"], answer: "Any object beyond Neptune" },
  { q: "What is the main composition of comets?", options: ["Ice and dust", "Metallic gas", "Heavy rocks"], answer: "Ice and dust" },
  { q: "Which planet has the shortest day?", options: ["Jupiter", "Saturn", "Neptune"], answer: "Jupiter" },
  { q: "What is a supermassive black hole?", options: ["A black hole at the center of galaxies", "A giant comet", "A giant neutron star"], answer: "A black hole at the center of galaxies" },
];

export default quizData;